@URL = http://localhost:3000

### Get all users
GET {{URL}}/api/user

### Create new user
POST {{URL}}/api/user
Content-Type: application/json

{
  "email": "mail@correo.com",
  "name": "Peter Parker",
  "password": "password1234"
}

### Get user by id
GET {{URL}}/api/user/d0511147-9488-4e9b-a11b-09de147dcc8d

### Update user password
POST {{URL}}/api/user/d0511147-9488-4e9b-a11b-09de147dcc8d
Content-Type: application/json

{
  "email": "mail@correo.com",
  "newPassword": "thisIsNewPass",
  "oldPassword": "password1234"
}

### Update existing user
PUT {{URL}}/api/user/d0511147-9488-4e9b-a11b-09de147dcc8d
Content-Type: application/json

{
  "email": "correo@correo.com",
  "name": "John Doe"
}

### Delete existing user
DELETE {{URL}}/api/user/d0511147-9488-4e9b-a11b-09de147dcc8d
Content-Type: application/json

{
  "email": "correo@correo.com",
  "password": "thisIsNewPass"
}

### Get all tasks
GET {{URL}}/api/task

### Create new task
POST {{URL}}/api/task
Content-Type: application/json

{
  "title": "Task 300",
  "description": "Description of the task 300",
  "userId": "e5c2a17f-ee5e-4b07-9c7d-3e69120d407f"
}

### GET task by id
GET {{URL}}/api/task/574f74f6-ff2c-4b17-a3ad-fb88894eb04d


### Update existing task
PUT {{URL}}/api/task/574f74f6-ff2c-4b17-a3ad-fb88894eb04d
Content-Type: application/json

{
  "title": "Edited task",
  "description": "New description for this task",
  "completed": true
}

### Delete task by id
DELETE {{URL}}/api/task/574f74f6-ff2c-4b17-a3ad-fb88894eb04d
